# Generated by Django 4.0.2 on 2022-03-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attending',
            field=models.ManyToManyField(blank=True, related_name='attending', to='events.Event'),
        ),
    ]
